import { createLogger } from '../../logger.js';
import type { AIOptions, AIProvider, ClassificationResult, RawResult } from '../types.js';

const log = createLogger('clde');

/**
 * Deterministic provider for flow tests. Pattern-matches the prompt to produce
 * a plausible response. Does NOT measure quality — only verifies pipelines run.
 */
export class MockProvider implements AIProvider {
  readonly name = 'mock';

  async classify(prompt: string, _options: AIOptions = {}): Promise<ClassificationResult> {
    const result = matchEmail(prompt);
    log.data('[mock] classify →', result);
    return result;
  }

  async classifyRaw(prompt: string, _options: AIOptions = {}): Promise<RawResult> {
    const result = matchInboxTask(prompt);
    log.data('[mock] classifyRaw →', result);
    return result;
  }

  async summarize(prompt: string, _options: AIOptions = {}): Promise<string> {
    if (/NINGUNO|ninguno/i.test(prompt)) return 'NINGUNO';
    return '• Mock resumen línea 1 (<https://example.com|r/mock>): contenido simulado.\n• Mock resumen línea 2 (<https://example.com|r/mock>): otro contenido.';
  }
}

function matchEmail(prompt: string): ClassificationResult {
  if (/security|login|alerta|2fa/i.test(prompt)) {
    return { classification: 'urgent', category: 'security', email_action: 'read', reason: 'mock' };
  }
  if (/factura|invoice|payment|recibo/i.test(prompt)) {
    return {
      classification: 'important',
      category: 'ticket',
      email_action: 'folder-tickets',
      amount: 250,
      amount_currency: 'PEN',
      reason: 'mock',
    };
  }
  if (/orden|order|envio|shipped/i.test(prompt)) {
    return { classification: 'informational', category: 'order', email_action: 'folder-orders', reason: 'mock' };
  }
  if (/promo|descuento|sale|oferta/i.test(prompt)) {
    return { classification: 'noise', category: 'promotion', email_action: 'trash', reason: 'mock' };
  }
  return { classification: 'informational', category: 'unknown', email_action: 'none', reason: 'mock' };
}

function matchInboxTask(prompt: string): RawResult {
  const lower = prompt.toLowerCase();
  let type = 'task';
  if (/proyecto|project/.test(lower)) type = 'project';
  else if (/idea|brainstorm/.test(lower)) type = 'idea';
  return {
    type,
    title: 'Mock task',
    description: 'Generated by MockProvider',
    priority: 30,
    energy: 50,
    context: 'personal',
    goal: null,
    subtasks: [],
    reasoning: 'mock',
  };
}
