/** Returns only the connection generated by the embedded PostgreSQL harness. */
export function testDatabaseUrl(): string {
  const connectionString = process.env.WINGMAN_TEST_DATABASE_URL;
  if (!connectionString) {
    throw new Error('PostgreSQL tests must run through the embedded harness');
  }
  return connectionString;
}
